# Image constants

IMAGE_HEIGHT = 480

# Houghline constants

HOUGH_MAX_LINE_GAP = 5
HOUGH_MIN_LINE_LENGTH = 50
HOUGH_THRESHOLD = 20

# Cluster constants

CLUSTER_MIN_SIZE = 10

# Pathfinder

NUMBER_OF_SUBDIVISIONS = 5

# Debug messages

DEBUG_MESSAGES = True

# Perspective transformation parameters
PAPER_DIMENSIION_HEIGHT = 11
PAPER_DIMENSION_WIDTH = 8.5
PERSPECTIVE_TRANSFORM_SCALE_FACTOR = 12
